--
-- PostgreSQL database dump
--

-- Dumped from database version 14.10 (Ubuntu 14.10-0ubuntu0.22.04.1)
-- Dumped by pg_dump version 14.10 (Ubuntu 14.10-0ubuntu0.22.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: all_warnings; Type: TABLE; Schema: public; Owner: ubiuser1
--

CREATE TABLE public.all_warnings (
    id integer NOT NULL,
    analyzed_files text,
    argno integer NOT NULL,
    lineno integer NOT NULL,
    function character varying(255) NOT NULL,
    warning text,
    file_num integer
);


ALTER TABLE public.all_warnings OWNER TO ubiuser1;

--
-- Name: all_warnings_id_seq; Type: SEQUENCE; Schema: public; Owner: ubiuser1
--

CREATE SEQUENCE public.all_warnings_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.all_warnings_id_seq OWNER TO ubiuser1;

--
-- Name: all_warnings_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: ubiuser1
--

ALTER SEQUENCE public.all_warnings_id_seq OWNED BY public.all_warnings.id;


--
-- Name: analysis_log; Type: TABLE; Schema: public; Owner: ubiuser1
--

CREATE TABLE public.analysis_log (
    item_id integer NOT NULL,
    test_round integer,
    dialog_id integer,
    req_abstract text,
    response text,
    model character varying,
    response_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.analysis_log OWNER TO ubiuser1;

--
-- Name: COLUMN analysis_log.req_abstract; Type: COMMENT; Schema: public; Owner: ubiuser1
--

COMMENT ON COLUMN public.analysis_log.req_abstract IS 'e.g., first 40 chars of request';


--
-- Name: case_sampling; Type: TABLE; Schema: public; Owner: ubiuser1
--

CREATE TABLE public.case_sampling (
    id integer NOT NULL,
    lineno integer NOT NULL,
    function character varying(255) NOT NULL,
    file character varying,
    var_name character varying,
    last_round integer DEFAULT 0,
    "group" integer,
    type character varying,
    notes character varying,
    raw_ctx text,
    ex boolean DEFAULT false
);


ALTER TABLE public.case_sampling OWNER TO ubiuser1;

--
-- Name: non_timout; Type: TABLE; Schema: public; Owner: ubiuser1
--

CREATE TABLE public.non_timout (
    id integer NOT NULL,
    alias_num integer,
    argno integer,
    bc character varying,
    function character varying,
    arg_id character varying,
    priority character varying,
    lineno integer,
    selected boolean DEFAULT false
);


ALTER TABLE public.non_timout OWNER TO ubiuser1;

--
-- Name: preprocess; Type: TABLE; Schema: public; Owner: ubiuser1
--

CREATE TABLE public.preprocess (
    id integer NOT NULL,
    function character varying,
    type character varying,
    var_name character varying,
    line_no integer,
    file character varying,
    preprocess text,
    raw_ctx text,
    analysis text,
    notes character varying,
    selected boolean DEFAULT false,
    priority character varying
);


ALTER TABLE public.preprocess OWNER TO ubiuser1;

--
-- Name: preprocess_id_seq; Type: SEQUENCE; Schema: public; Owner: ubiuser1
--

ALTER TABLE public.preprocess ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.preprocess_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: preprocess_log; Type: TABLE; Schema: public; Owner: ubiuser1
--

CREATE TABLE public.preprocess_log (
    item_id integer NOT NULL,
    response1 text,
    response2 text,
    model character varying,
    respond_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.preprocess_log OWNER TO ubiuser1;

--
-- Name: sampling_res; Type: TABLE; Schema: public; Owner: ubiuser1
--

CREATE TABLE public.sampling_res (
    id integer NOT NULL,
    model character varying NOT NULL,
    result character varying,
    "group" integer,
    initializer character varying,
    stable boolean
);


ALTER TABLE public.sampling_res OWNER TO ubiuser1;

--
-- Name: timout; Type: TABLE; Schema: public; Owner: ubiuser1
--

CREATE TABLE public.timout (
    id integer NOT NULL,
    analyzed_files text,
    argno integer NOT NULL,
    lineno integer NOT NULL,
    function character varying(255) NOT NULL,
    warning text,
    file_num integer,
    arg_id character varying
);


ALTER TABLE public.timout OWNER TO ubiuser1;

--
-- Name: all_warnings id; Type: DEFAULT; Schema: public; Owner: ubiuser1
--

ALTER TABLE ONLY public.all_warnings ALTER COLUMN id SET DEFAULT nextval('public.all_warnings_id_seq'::regclass);


--
-- Name: all_warnings all_warnings_pkey; Type: CONSTRAINT; Schema: public; Owner: ubiuser1
--

ALTER TABLE ONLY public.all_warnings
    ADD CONSTRAINT all_warnings_pkey PRIMARY KEY (id);


--
-- Name: non_timout non_timout_pk; Type: CONSTRAINT; Schema: public; Owner: ubiuser1
--

ALTER TABLE ONLY public.non_timout
    ADD CONSTRAINT non_timout_pk PRIMARY KEY (id);


--
-- Name: case_sampling preprocess2_pkey; Type: CONSTRAINT; Schema: public; Owner: ubiuser1
--

ALTER TABLE ONLY public.case_sampling
    ADD CONSTRAINT preprocess2_pkey PRIMARY KEY (id);


--
-- Name: preprocess preprocess_pk; Type: CONSTRAINT; Schema: public; Owner: ubiuser1
--

ALTER TABLE ONLY public.preprocess
    ADD CONSTRAINT preprocess_pk PRIMARY KEY (id);


--
-- Name: sampling_res sampling_res_pk; Type: CONSTRAINT; Schema: public; Owner: ubiuser1
--

ALTER TABLE ONLY public.sampling_res
    ADD CONSTRAINT sampling_res_pk PRIMARY KEY (id, model);


--
-- Name: timout timout_pkey; Type: CONSTRAINT; Schema: public; Owner: ubiuser1
--

ALTER TABLE ONLY public.timout
    ADD CONSTRAINT timout_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

